"""warnings_agregados

Revision ID: 38fff6310a08
Revises: 40dfa80b4991
Create Date: 2026-06-15 11:58:58.825591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '38fff6310a08'
down_revision: Union[str, Sequence[str], None] = '40dfa80b4991'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warnings_por_mes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turbina_id', sa.Integer(), nullable=False),
    sa.Column('carga_id', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['carga_id'], ['cargas.id'], ),
    sa.ForeignKeyConstraint(['turbina_id'], ['turbinas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('turbina_id', 'mes', 'anio', name='uq_warning_mes_turbina_periodo')
    )
    op.create_table('warnings_por_tipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turbina_id', sa.Integer(), nullable=False),
    sa.Column('carga_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=True),
    sa.Column('anio', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['carga_id'], ['cargas.id'], ),
    sa.ForeignKeyConstraint(['turbina_id'], ['turbinas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('turbina_id', 'tipo', 'mes', 'anio', name='uq_warning_tipo_turbina_tipo_periodo')
    )
    op.drop_table('warnings_rodamientos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warnings_rodamientos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('turbina_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('carga_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha_inicio', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('fecha_fin', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('mes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('anio', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo_warning', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('duracion_horas', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('potencia_kw', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('viento_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['carga_id'], ['cargas.id'], name=op.f('warnings_rodamientos_carga_id_fkey')),
    sa.ForeignKeyConstraint(['turbina_id'], ['turbinas.id'], name=op.f('warnings_rodamientos_turbina_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('warnings_rodamientos_pkey')),
    sa.UniqueConstraint('turbina_id', 'fecha_inicio', 'tipo_warning', name=op.f('uq_warning_turbina_fecha_tipo'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('warnings_por_tipo')
    op.drop_table('warnings_por_mes')
    # ### end Alembic commands ###
