"""tablas_iniciales

Revision ID: 40dfa80b4991
Revises: 
Create Date: 2026-06-15 10:52:57.448441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40dfa80b4991'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parques',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('cantidad_turbinas', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('cargas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parque_id', sa.Integer(), nullable=False),
    sa.Column('tipo_archivo', sa.String(length=20), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=255), nullable=False),
    sa.Column('fecha_carga', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('registros_insertados', sa.Integer(), nullable=True),
    sa.Column('notas', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['parque_id'], ['parques.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turbinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parque_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['parque_id'], ['parques.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inspecciones_rodamientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turbina_id', sa.Integer(), nullable=False),
    sa.Column('carga_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tipo_evento', sa.String(length=100), nullable=False),
    sa.Column('categoria_delantera', sa.String(length=5), nullable=False),
    sa.Column('categoria_trasera', sa.String(length=5), nullable=False),
    sa.Column('cambio_rodamiento_delantero', sa.Date(), nullable=True),
    sa.Column('cambio_rodamiento_trasero', sa.Date(), nullable=True),
    sa.Column('comentarios', sa.String(length=500), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['carga_id'], ['cargas.id'], ),
    sa.ForeignKeyConstraint(['turbina_id'], ['turbinas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('turbina_id', 'fecha', name='uq_inspeccion_turbina_fecha')
    )
    op.create_table('warnings_rodamientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turbina_id', sa.Integer(), nullable=False),
    sa.Column('carga_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('tipo_warning', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('duracion_horas', sa.Float(), nullable=True),
    sa.Column('potencia_kw', sa.Float(), nullable=True),
    sa.Column('viento_ms', sa.Float(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['carga_id'], ['cargas.id'], ),
    sa.ForeignKeyConstraint(['turbina_id'], ['turbinas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('turbina_id', 'fecha_inicio', 'tipo_warning', name='uq_warning_turbina_fecha_tipo')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('warnings_rodamientos')
    op.drop_table('inspecciones_rodamientos')
    op.drop_table('turbinas')
    op.drop_table('cargas')
    op.drop_table('parques')
    # ### end Alembic commands ###
